### PR TITLE
delete failed job when rerun failed job

### PR DESCRIPTION
**Pull request by kaisco**

### CODE REVIEW

**Comment by austinkregel** [comment]
Just because it's been a while since I've touched my own code here, what would be the reason to delete the job? 
Is it to pull it out of the job queue? Or to delete the record of the failed job? From my quick look at my code it looks like it will just delete the record of the failed job.

**Comment by kaisco** [comment]
Thanks for your reply,  I just wanna know which job I was rerun and I think the rerun job should be deleted.

**Comment by austinkregel** [comment]
Ah! Gotcha, I think if we're going to delete the job we should implement soft deletes, then all `deleted_at` timestamps can be treated as the time it was retried. And it doesn't delete any historical data.

Would you mind implementing soft deletes for this PR? All that should need to be done is to add the migration, have the ToolServiceProvider publish it, and add the soft deletes trait to the Failed job model.

**Comment by kaisco** [comment]
I have tried your solution. But I don't know how does soft deletes work on the command line(``php artisan queue:retry/queue:list/…``)?
I think It's OK force deletes.

**Comment by austinkregel** [comment]
Oh my apologies! Soft deletes would not be done as a command line argument, they would be done on the [FailedJob](https://github.com/austinkregel/nova-failed-jobs-tool/blob/master/src/Models/FailedJob.php) model. Laravel offers a trait to "enable" soft deletes.

I'll merge your, PR in but I'm going to add the soft delete functionality before I mark a new release.

**Pull request merged**
